/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainWindow.java
 *
 * Created on Sep 24, 2011, 8:53:03 AM
 */
package imgageviewer;

import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author kynku
 */
public class MainWindow extends javax.swing.JFrame {

    /** Creates new form MainWindow */
    public MainWindow() {
        initComponents();

        //file dialog section
        this.currentImage = -1;
        this.filter = new FileNameExtensionFilter("JPG ,GIF ,PNG, BMP", "bmp", "jpg", "gif", "png");
        this.fileDialog = new JFileChooser();
        this.fileDialog.setFileFilter(filter);
        this.fileDialogFrame = new JDialog(this, "Abrir archivo...", true);
        this.fileDialogFrame.add(fileDialog);
        this.fileDialogFrame.pack();
        this.graphics = (Graphics2D) this.renderingPanel.getGraphics();
        this.graphicsGray = (Graphics2D) this.panelGray.getGraphics();
        this.graphicsSobel = (Graphics2D) this.panelSobel.getGraphics();

        this.challengeAccepted = new ChallengePanel();
        this.challengeAccepted.setSize(this.renderingPanel.getSize());
        this.renderingPanel.add(this.challengeAccepted);
        this.filter_challenge = new ChallengeFilter();
        
        this.panelGray_ = new ChallengePanel();
        this.panelGray_.setSize(this.panelGray.getSize());
        this.panelGray.add(this.panelGray_);
        
        this.panelSobel_ = new ChallengePanel();
        this.panelSobel_.setSize(this.panelSobel.getSize());
        this.panelSobel.add(this.panelSobel_);
        
        

        this.aboutImage = new ImageIcon(MainWindow.class.getResource("Resources/Duff_Beer.jpg"));
        this.trollImage = new ImageIcon(MainWindow.class.getResource("Resources/Trollface.png"));

        this.setTitle("Image Viewver");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelGray = new javax.swing.JTabbedPane();
        renderingPanel = new javax.swing.JPanel();
        panelSobel = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        sobelButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        previousButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        abrirMenuItem = new javax.swing.JMenuItem();
        salirMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(1, 20));

        renderingPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout renderingPanelLayout = new javax.swing.GroupLayout(renderingPanel);
        renderingPanel.setLayout(renderingPanelLayout);
        renderingPanelLayout.setHorizontalGroup(
            renderingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 808, Short.MAX_VALUE)
        );
        renderingPanelLayout.setVerticalGroup(
            renderingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 461, Short.MAX_VALUE)
        );

        panelGray.addTab("Main Image", renderingPanel);
        panelGray.addTab("Sobel Filter", panelSobel);
        panelGray.addTab("RGB->GrayScale", jTabbedPane3);

        sobelButton.setText("Apply Sobel Filter");

        nextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgageviewer/Resources/media-skip-forward.png"))); // NOI18N
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        previousButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgageviewer/Resources/media-skip-backward.png"))); // NOI18N
        previousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(previousButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nextButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sobelButton))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(previousButton)
                    .addComponent(nextButton)
                    .addComponent(sobelButton))
                .addContainerGap())
        );

        jMenu1.setMnemonic('a');
        jMenu1.setText("Archivo...");

        abrirMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        abrirMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgageviewer/Resources/document-open.png"))); // NOI18N
        abrirMenuItem.setMnemonic('a');
        abrirMenuItem.setText("Abrir");
        abrirMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(abrirMenuItem);

        salirMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        salirMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgageviewer/Resources/document-close.png"))); // NOI18N
        salirMenuItem.setMnemonic('s');
        salirMenuItem.setText("Salir");
        salirMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(salirMenuItem);
        jMenu1.add(jSeparator1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Acerca de...");

        jMenuItem1.setText("Acerca de Image Viewer...");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(294, 294, 294))
            .addGroup(layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(301, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGray, javax.swing.GroupLayout.DEFAULT_SIZE, 813, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGray, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
        if (this.currentImage != this.imageList.size() - 1) {
            this.challengeAccepted.setImage(this.imageList.get(++this.currentImage));
            this.setTitle(this.nameList.get(this.currentImage));
        }
    }//GEN-LAST:event_nextButtonActionPerformed

    private void abrirMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirMenuItemActionPerformed

        int returnVal = fileDialog.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            //File file = fileDialog.getSelectedFile();
            //String filename = this.fileDialog.getName(null);
            // System.out.println("ruta?: " + file);
            try {
                //BufferedImage imagen = ImageIO.read(file);
                this.loadImages(fileDialog.getCurrentDirectory(), fileDialog.getSelectedFile());
                this.challengeAccepted.setImage(this.imageList.get(this.currentImage));
                this.setTitle(this.nameList.get(this.currentImage));
            } catch (IOException ex) {        
            JOptionPane.showMessageDialog(null,
                "Ha ocurrido un error. Contacte con su administrador.",
                "Problem?",
                JOptionPane.INFORMATION_MESSAGE,
                this.trollImage);

            }
        } else {
            //no hace nada
        }


    }//GEN-LAST:event_abrirMenuItemActionPerformed

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
        // TODO add your handling code here:
        if (this.currentImage != 0) {
            this.challengeAccepted.setImage(this.imageList.get(--this.currentImage));
            this.setTitle(this.nameList.get(this.currentImage));
        }
    }//GEN-LAST:event_previousButtonActionPerformed

    private void salirMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirMenuItemActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:

        JOptionPane.showMessageDialog(this,
                "Laboratorio de programacion que vale por toda la unidad 3\n"
                + "hecho por Erik Andres (kynku) Regla Torres.",
                "Acerca de ImageViewver",
                JOptionPane.INFORMATION_MESSAGE,
                this.aboutImage);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        // TODO add your handling code here:
        this.challengeAccepted.setSize(this.renderingPanel.getSize());
        this.challengeAccepted.setImage(this.imageList.get(this.currentImage));
    }//GEN-LAST:event_formWindowStateChanged

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
        if (this.currentImage != -1) {
            this.challengeAccepted.setSize(this.renderingPanel.getSize());
            this.challengeAccepted.setImage(this.imageList.get(this.currentImage));
        }
    }//GEN-LAST:event_formComponentResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    public void loadImages(File directory, File wished) throws IOException {
        this.setTitle("Cargando Imagenes...");
        this.imageList = new ArrayList<BufferedImage>();
        this.nameList = new ArrayList<String>();
        File[] fileList = directory.listFiles();
        for (File s : fileList) {
            if (this.filter_challenge.accept(s)) {
                this.imageList.add(ImageIO.read(s));
                this.nameList.add(s.getName());
                if (s.equals(wished)) {
                    this.currentImage = this.imageList.size() - 1;
                }
            }
        }
    }
    private Icon aboutImage;
    private JFileChooser fileDialog;
    private JDialog fileDialogFrame;
    private FileNameExtensionFilter filter;
    private ChallengeFilter filter_challenge;
    private Graphics2D graphics, graphicsGray, graphicsSobel;
    private ChallengePanel challengeAccepted;
    private ChallengePanel panelSobel_;
    private ChallengePanel panelGray_;
    private int currentImage;
    private ImageIcon trollImage;
    ArrayList<BufferedImage> imageList;
    ArrayList<String> nameList;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abrirMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JButton nextButton;
    private javax.swing.JTabbedPane panelGray;
    private javax.swing.JTabbedPane panelSobel;
    private javax.swing.JButton previousButton;
    private javax.swing.JPanel renderingPanel;
    private javax.swing.JMenuItem salirMenuItem;
    private javax.swing.JButton sobelButton;
    // End of variables declaration//GEN-END:variables
}
