SELECT * FROM problems WHERE letter = 'a';
SELECT * FROM problems WHERE letter = 'B';
SELECT * FROM problems WHERE letter = 'Q';
SELECT * FROM problems WHERE letter = 'k';
SELECT * FROM problems WHERE letter = 'o';
SELECT problems.id,problems.letter,problems.pdf_file,problems.ballon_colour,problems.description,problems.codename FROM problems,problem_set,contests WHERE problem_set.problem_id = problems.id AND problem_set.contest_id = contests.id AND contests.name = 'rrevanamuclefagla';
SELECT problems.id,problems.letter,problems.pdf_file,problems.ballon_colour,problems.description,problems.codename FROM problems,problem_set,contests WHERE problem_set.problem_id = problems.id AND problem_set.contest_id = contests.id AND contests.name = 'heochuiplirroedebokeerreobre';
SELECT problems.id,problems.letter,problems.pdf_file,problems.ballon_colour,problems.description,problems.codename FROM problems,problem_set,contests WHERE problem_set.problem_id = problems.id AND problem_set.contest_id = contests.id AND contests.name = 'obropifuepogiquwecluoglechezojuka';
SELECT problems.id,problems.letter,problems.pdf_file,problems.ballon_colour,problems.description,problems.codename FROM problems,problem_set,contests WHERE problem_set.problem_id = problems.id AND problem_set.contest_id = contests.id AND contests.name = 'cluplaqoblarriicaunagi';
SELECT problems.id,problems.letter,problems.pdf_file,problems.ballon_colour,problems.description,problems.codename FROM problems,problem_set,contests WHERE problem_set.problem_id = problems.id AND problem_set.contest_id = contests.id AND contests.name = 'uqugrodixucliclellotodrofuovohe';
SELECT teams.id,teams.name FROM teams,sites,countries WHERE teams.site_id = sites.id AND sites.country_id = countries.id AND countries.name = 'huiqiblayobujezohoayi';
SELECT teams.id,teams.name FROM teams,sites,countries WHERE teams.site_id = sites.id AND sites.country_id = countries.id AND countries.name = 'yeepegrarruebrayi';
SELECT teams.id,teams.name FROM teams,sites,countries WHERE teams.site_id = sites.id AND sites.country_id = countries.id AND countries.name = 'juzouvaplufolerrohahublunuugloxa';
SELECT teams.id,teams.name FROM teams,sites,countries WHERE teams.site_id = sites.id AND sites.country_id = countries.id AND countries.name = 'cliglodriomovofabruubuxacahu';
SELECT teams.id,teams.name FROM teams,sites,countries WHERE teams.site_id = sites.id AND sites.country_id = countries.id AND countries.name = 'sagleqehellomuezazaguhagradreewu';
SELECT teams.id,teams.name FROM teams,team_members WHERE team_members.team_id = teams.id AND team_members.contestant_id = 5366;
SELECT teams.id,teams.name FROM teams,team_members WHERE team_members.team_id = teams.id AND team_members.contestant_id = 30686;
SELECT teams.id,teams.name FROM teams,team_members WHERE team_members.team_id = teams.id AND team_members.contestant_id = 98;
SELECT teams.id,teams.name FROM teams,team_members WHERE team_members.team_id = teams.id AND team_members.contestant_id = 567;
SELECT teams.id,teams.name FROM teams,team_members WHERE team_members.team_id = teams.id AND team_members.contestant_id = 783549;
SELECT * FROM problems WHERE ballon_colour = 'orange';
SELECT * FROM problems WHERE ballon_colour = 'blue';
SELECT * FROM problems WHERE ballon_colour = 'black';
SELECT * FROM problems WHERE ballon_colour = 'crimson';
SELECT * FROM problems WHERE ballon_colour = 'indigo';