/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Battle.java
 *
 * Created on 08-12-2009, 04:38:18 PM
 */

package day_of_sagitarius;

import java.awt.GridLayout;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author kuroneko
 */
public class Battle extends javax.swing.JPanel {

    JLabel[][] botones;
    JLabel[][] botones2;
    Day_Of_SagitariusView root;
    private ImageIcon rojo;
    private ImageIcon negro;
    private ImageIcon verde;
    int l_i, l_j;
    /** Creates new form Battle */
    public Battle(Day_Of_SagitariusView root) {
        initComponents();
        this.root = root;
        this.verde = new ImageIcon(ImageIcon.class.getResource("/Images/estrellasverde.gif"));
        this.negro = new ImageIcon(ImageIcon.class.getResource("/Images/estrellasfondo.gif"));
        this.rojo = new ImageIcon(ImageIcon.class.getResource("/Images/estrellasrojas.gif"));
        botones = new JLabel[10][10];
        botones2 = new JLabel[10][10];
        this.jPanel1.setLayout(new GridLayout(10,10));
        for(int i=0;i<10;i++){
            for(int j=0;j<10;j++){
                this.botones[i][j] = new JLabel(this.negro);
                if(this.root.player.grid[i][j]==0){
                    this.botones[i][j].setText("empty");}
                else{
                    this.botones[i][j].setText("alive");
                    this.botones[i][j].setIcon(this.verde);
                }
                this.jPanel1.add(this.botones[i][j]);
                this.botones[i][j].setSize(15, 15);
                this.jPanel1.add(this.botones[i][j]);
            }
        }
        this.jPanel1.setOpaque(false);

        this.jPanel2.setLayout(new GridLayout(10,10));
        for(int i=0;i<10;i++){
            for(int j=0;j<10;j++){
                this.botones2[i][j] = new JLabel(this.negro);
                if(this.root.player2.grid[i][j]==0)
                    this.botones2[i][j].setText("empty");
                else{
                    this.botones2[i][j].setText("alive");
                }
                this.jPanel2.add(this.botones[i][j]);
                this.botones2[i][j].setSize(15, 15);
                this.jPanel2.add(this.botones2[i][j]);
            }
        }
        this.jPanel2.setOpaque(false);
        this.aiming = false;
        while(true){
            try {
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                Logger.getLogger(Battle.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(aiming==false){
                try {
                    this.jPanel2.setVisible(false);
                    String shoot = this.root.conexion.input.readLine();
                    if(shoot.equals("hit")){
                        shoot = this.root.conexion.input.readLine();
                        this.botones2[this.l_i][this.l_j].setIcon(this.rojo);
                    }
                    char[] valor = shoot.toCharArray();
                    if(this.botones[valor[0]][valor[2]].getName() == "alive"){
                        this.botones[valor[0]][valor[2]].setName("owned");
                        this.botones[valor[0]][valor[2]].setIcon(this.rojo);
                        this.root.conexion.output.println("hit");
                    }
                } catch (IOException ex) {
                    Logger.getLogger(Battle.class.getName()).log(Level.SEVERE, null, ex);
                }
                this.aiming = true;
            }
        }
    }

    public void shoot(int i, int j){
        this.root.conexion.output.println(i+","+j);
        this.botones2[i][j].setIcon(this.verde);
        this.aiming=false;
        this.l_i=i;
        this.l_j=j;
    }
    public boolean shooted, aiming;
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setName("Form"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(day_of_sagitarius.Day_Of_SagitariusApp.class).getContext().getResourceMap(Battle.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jPanel2.setName("jPanel2"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setName("jTextArea1"); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
