SELECT * FROM d1_problems WHERE letter = 'a';
SELECT * FROM d1_problems WHERE letter = 'B';
SELECT * FROM d1_problems WHERE letter = 'Q';
SELECT * FROM d1_problems WHERE letter = 'k';
SELECT * FROM d1_problems WHERE letter = 'o';
SELECT d2_problems.id,d2_problems.letter,d2_problems.pdf_file,d2_problems.ballon_colour,d2_problems.description,d2_problems.codename FROM d2_problems WHERE contest_name = 'rrevanamuclefagla';
SELECT d2_problems.id,d2_problems.letter,d2_problems.pdf_file,d2_problems.ballon_colour,d2_problems.description,d2_problems.codename FROM d2_problems WHERE contest_name = 'heochuiplirroedebokeerreobre';
SELECT d2_problems.id,d2_problems.letter,d2_problems.pdf_file,d2_problems.ballon_colour,d2_problems.description,d2_problems.codename FROM d2_problems WHERE contest_name = 'obropifuepogiquwecluoglechezojuka';
SELECT d2_problems.id,d2_problems.letter,d2_problems.pdf_file,d2_problems.ballon_colour,d2_problems.description,d2_problems.codename FROM d2_problems WHERE contest_name = 'cluplaqoblarriicaunagi';
SELECT d2_problems.id,d2_problems.letter,d2_problems.pdf_file,d2_problems.ballon_colour,d2_problems.description,d2_problems.codename FROM d2_problems WHERE contest_name = 'uqugrodixucliclellotodrofuovohe';
SELECT d3_teams.id,d3_teams.name FROM d3_teams,countries WHERE countries.id = d3_teams.country_id AND countries.name = 'huiqiblayobujezohoayi';
SELECT d3_teams.id,d3_teams.name FROM d3_teams,countries WHERE countries.id = d3_teams.country_id AND countries.name = 'yeepegrarruebrayi';
SELECT d3_teams.id,d3_teams.name FROM d3_teams,countries WHERE countries.id = d3_teams.country_id AND countries.name = 'juzouvaplufolerrohahublunuugloxa';
SELECT d3_teams.id,d3_teams.name FROM d3_teams,countries WHERE countries.id = d3_teams.country_id AND countries.name = 'cliglodriomovofabruubuxacahu';
SELECT d3_teams.id,d3_teams.name FROM d3_teams,countries WHERE countries.id = d3_teams.country_id AND countries.name = 'sagleqehellomuezazaguhagradreewu';
SELECT d4_team_members.team_id,d4_team_members.team_name FROM d4_team_members WHERE d4_team_members.contestant_id = 5366;
SELECT d4_team_members.team_id,d4_team_members.team_name FROM d4_team_members WHERE d4_team_members.contestant_id = 30686;
SELECT d4_team_members.team_id,d4_team_members.team_name FROM d4_team_members WHERE d4_team_members.contestant_id = 98;
SELECT d4_team_members.team_id,d4_team_members.team_name FROM d4_team_members WHERE d4_team_members.contestant_id = 567;
SELECT d4_team_members.team_id,d4_team_members.team_name FROM d4_team_members WHERE d4_team_members.contestant_id = 783549;
SELECT d5_problems.id,d5_problems.letter,d5_problems.pdf_file,d5_colours.name,d5_problems.description,d5_problems.codename FROM d5_problems,d5_colours WHERE d5_problems.colour_id = d5_colours.id AND d5_colours.name = 'orange';
SELECT d5_problems.id,d5_problems.letter,d5_problems.pdf_file,d5_colours.name,d5_problems.description,d5_problems.codename FROM d5_problems,d5_colours WHERE d5_problems.colour_id = d5_colours.id AND d5_colours.name = 'blue';
SELECT d5_problems.id,d5_problems.letter,d5_problems.pdf_file,d5_colours.name,d5_problems.description,d5_problems.codename FROM d5_problems,d5_colours WHERE d5_problems.colour_id = d5_colours.id AND d5_colours.name = 'black';
SELECT d5_problems.id,d5_problems.letter,d5_problems.pdf_file,d5_colours.name,d5_problems.description,d5_problems.codename FROM d5_problems,d5_colours WHERE d5_problems.colour_id = d5_colours.id AND d5_colours.name = 'crimson';
SELECT d5_problems.id,d5_problems.letter,d5_problems.pdf_file,d5_colours.name,d5_problems.description,d5_problems.codename FROM d5_problems,d5_colours WHERE d5_problems.colour_id = d5_colours.id AND d5_colours.name = 'indigo';